# Generated by Django 3.1.7 on 2021-03-03 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=64)),
                ('is_boss_level', models.BooleanField(default=False)),
                ('is_final_boss_level', models.BooleanField(default=False)),
                ('is_start_node', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=1000)),
                ('difficulty', models.CharField(choices=[('1', 'Easy'), ('2', 'Normal'), ('3', 'Hard')], max_length=1)),
                ('time_created', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_user_fk', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('world_name', models.CharField(max_length=64)),
                ('topic', models.CharField(max_length=64)),
                ('is_custom_world', models.BooleanField(default=False)),
                ('index', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserWorldProgressRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('started_time', models.DateTimeField(auto_now=True)),
                ('completed_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userworldprogressrecord_user_fk', to=settings.AUTH_USER_MODEL)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userworldprogressrecord_world_fk', to='main.world')),
            ],
        ),
        migrations.CreateModel(
            name='UserLevelProgressRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('started_time', models.DateTimeField(auto_now=True)),
                ('completed_time', models.DateTimeField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userlevelprogressrecord_level_fk', to='main.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userlevelprogressrecord_user_fk', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_topic_name', models.CharField(max_length=30)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_world_fk', to='main.world')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_change', models.IntegerField()),
                ('reason', models.CharField(max_length=256)),
                ('time', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionrecord_question_fk', to='main.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionrecord_user_fk', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_world_fk', to='main.world'),
        ),
        migrations.CreateModel(
            name='LevelPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levelpath_fromlevel_fk', to='main.level')),
                ('to_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levelpath_tolevel_fk', to='main.level')),
            ],
        ),
        migrations.AddField(
            model_name='level',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_section_fk', to='main.section'),
        ),
        migrations.CreateModel(
            name='CustomWorld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_code', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('created_date', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_world_user_fk', to=settings.AUTH_USER_MODEL)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_world_world_fk', to='main.world')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_index', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('deadline', models.DateTimeField(auto_now=True)),
                ('custom_world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_custom_world_fk', to='main.customworld')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=256)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_question_fk', to='main.question')),
            ],
        ),
    ]
