# Generated by Django 3.1.7 on 2021-03-06 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='index',
            field=models.IntegerField(default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='index',
            field=models.IntegerField(default=None, null=True, unique=True),
        ),
    ]
